DELETE FROM likes;
DELETE FROM film_genre;
DELETE FROM films;
DELETE FROM users;
DELETE FROM reviews;
DELETE FROM review_likes;
DELETE FROM review_dislikes;

ALTER TABLE users ALTER COLUMN user_id RESTART WITH 1;
ALTER TABLE films ALTER COLUMN film_id RESTART WITH 1;
ALTER TABLE likes ALTER COLUMN id RESTART WITH 1;
ALTER TABLE film_genre ALTER COLUMN id RESTART WITH 1;
ALTER TABLE reviews ALTER COLUMN id RESTART WITH 1;